name:  Actualizaci贸n de Documentaci贸n
description: Crear o actualizar documentaci贸n del proyecto
title: '[DOCS] - '
labels: [documentation]
assignees:
    - HormigaDev
body:
    - type: textarea
      id: doc-section
      attributes:
          label:  Secci贸n a Documentar
          description: 驴Qu茅 parte del proyecto se est谩 documentando?
      validations:
          required: true

    - type: textarea
      id: content
      attributes:
          label: 锔 Contenido a Incluir
          description: Explica los puntos clave que se deben documentar.
      validations:
          required: true

    - type: textarea
      id: purpose
      attributes:
          label:  Prop贸sito
          description: 驴Qu茅 problema resuelve esta documentaci贸n?
      validations:
          required: true

    - type: input
      id: related-code
      attributes:
          label:  Relaci贸n con C贸digo
          placeholder: Ej. src/modules/auth.ts, commit abc123
