name: 🚨 Essential Task
description: Tarea crítica para mantener la funcionalidad base del proyecto
title: '[ESSENTIAL] - '
labels: [enhancement]
assignees:
    - HormigaDev
body:
    - type: textarea
      id: task-description
      attributes:
          label: 🔧 Descripción de la Tarea
      validations:
          required: true

    - type: textarea
      id: goal
      attributes:
          label: 🎯 Objetivo
      validations:
          required: true

    - type: dropdown
      id: priority
      attributes:
          label: 📌 Prioridad
          options:
              - Crítica
              - Alta
              - Media
              - Baja
      validations:
          required: true

    - type: checkboxes
      id: acceptance-criteria
      attributes:
          label: 📝 Criterios de Aceptación
          options:
              - label: Todos los endpoints o funcionalidades relacionadas funcionan correctamente
              - label: Código documentado conforme al estándar del proyecto
              - label: Cumple con las normas de estilo y linters
              - label: No introduce regresiones
              - label: Cumple con requisitos de performance mínimos

    - type: input
      id: eta
      attributes:
          label: ⏱ ETA Estimada
          placeholder: Ej. 3 días
